### ISSUE TITLE
Install error?

### ISSUE THREAD

**Issue by psychemedia** [genepattern/jupyter-wysiwyg#4] opened 2018-04-23 12:11 UTC
I'm currently getting the following install error trying to install `jupyter_wysiwyg`:

`error: can't copy 'jupyter_wysiwyg/static/ckeditor': doesn't exist or not a regular file`

**Comment by tmtabor** [comment] 2018-04-23 16:19
Are you trying to install through PIP, conda or from source? 

I have the feeling that this may be an issue with an install script not bundling that subdirectory correctly.

**Comment by psychemedia** [comment] 2018-04-24 15:46
Using pip - either from pypi or from this repo.

**Comment by tmtabor** [comment] 2018-04-25 18:41
So far I've been unable to reproduce this. There is a known bug in setuptools that can result in this error when using Python 2.7.6, but I'm going to assume you're probably using a more recent version of Python than that.

So for my own debugging purposes, what version of Python are you using and what operating system are you seeing this on?

**Comment by psychemedia** [comment] 2018-04-26 09:54
I'm on 3.5.2 in Ubuntu 16.04.4 LTS xenial.

Other projects seem to be reporting similar issues - with a workaround of being more explicit on files to copy. eg https://github.com/lwneal/gnomehat/commit/12c6bea8bf32df4096a22f3ee887d3633c0be26d

**Comment by tmtabor** [comment] 2018-04-26 20:02
Thanks for the info!

I've checked in a fix. In theory, you should be able to install from this repo. Once I've verified the fix works, I'll push it to PyPI / conda.

**Comment by psychemedia** [comment] 2018-04-26 20:27
Install from the repo seems to work for me now... Thanks:-)

**Comment by tmtabor** [comment] 2018-04-26 20:28
Thank you letting me know of the issue! I will mark it as closed and push to PyPI / conda.

**Closed as completed** 2018-04-26 20:28 UTC
